# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank=True, upload_to='competition_image'),
        ),
    ]
