# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_competition'),
        ('competitions', '0002_competition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='team',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
