# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20170624_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to='player_image'),
        ),
    ]
