# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 04:10
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
