# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:21
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
