# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
