# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0003_stadium_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ManyToManyField(to='competitions.Competition'),
        ),
    ]
