# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170702_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competition',
        ),
    ]
