# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20170716_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_stadium', to='teams.Team'),
        ),
    ]
