# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 15:49
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_pointofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
