# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 14:35
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_stadium_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
